-- World Languages (ISO 639)
-- SQL Table | v1.1.0 (2022)
-- https://github.com/ccmars/world-data

DROP TABLE IF EXISTS `world_languages`;
CREATE TABLE `world_languages` (
  `alpha2` varchar(2) NOT NULL,
  `langEN` varchar(48) NOT NULL,
  `langDE` varchar(48) NOT NULL,
  `langFR` varchar(48) NOT NULL,
  `langES` varchar(48) NOT NULL,
  `langIT` varchar(48) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=UTF8MB4 COMMENT='World Languages (ISO 639)';

INSERT INTO `world_languages` (`alpha2`, `langEN`, `langDE`, `langFR`, `langES`, `langIT`) VALUES
('aa', 'Afar', 'Danakil-Sprache', 'afar', 'afar', 'Afar'),
('ab', 'Abkhazian', 'Abchasisch', 'abkhaze', 'abjaso', 'Abkhaz'),
('ae', 'Avestan', 'Avestisch', 'avestique', 'avéstico', 'Avestico'),
('af', 'Afrikaans', 'Afrikaans', 'afrikaans', 'afrikaans', 'Afrikaans'),
('ak', 'Akan', 'Akan-Sprache', 'akan', 'akano', 'Akan'),
('am', 'Amharic', 'Amharisch', 'amharique', 'amárico', 'Amarico'),
('an', 'Aragonese', 'Aragonesisch', 'aragonais', 'aragonés', 'Aragonese'),
('ar', 'Arabic', 'Arabisch', 'arabe', 'árabe', 'Arabo'),
('as', 'Assamese', 'Assamesisch', 'assamais', 'asamés', 'Assamese'),
('av', 'Avaric', 'Awarisch', 'avar', 'avar', 'Avaro'),
('ay', 'Aymara', 'Aymará-Sprache', 'aymara', 'aimara', 'Aymara'),
('az', 'Azerbaijani', 'Aserbeidschanisch', 'azéri', 'azerí', 'Azero'),
('ba', 'Bashkir', 'Baschkirisch', 'bachkir', 'baskir', 'Bashkir'),
('be', 'Belarusian', 'Weißrussisch', 'biélorusse', 'bielorruso', 'Bielorusso'),
('bg', 'Bulgarian', 'Bulgarisch', 'bulgare', 'búlgaro', 'Bulgaro'),
('bi', 'Bislama', 'Beach-la-mar', 'bichlamar', 'bislama', 'Bislama'),
('bm', 'Bambara', 'Bambara-Sprache', 'bambara', 'bambara', 'Bambara'),
('bn', 'Bengali', 'Bengali', 'bengali', 'bengalí', 'Bengalese'),
('bo', 'Tibetan', 'Tibetisch', 'tibétain', 'tibetano', 'Tibetano'),
('br', 'Breton', 'Bretonisch', 'breton', 'bretón', 'Bretone'),
('bs', 'Bosnian', 'Bosnisch', 'bosniaque', 'bosnio', 'Bosniaco'),
('ca', 'Catalan', 'Katalanisch', 'catalan', 'catalán', 'Catalano'),
('ce', 'Chechen', 'Tschetschenisch', 'tchétchène', 'checheno', 'Ceceno'),
('ch', 'Chamorro', 'Chamorro-Sprache', 'chamorro', 'chamorro', 'Chamorro'),
('co', 'Corsican', 'Korsisch', 'corse', 'corso', 'Corso'),
('cr', 'Cree', 'Cree-Sprache', 'cree', 'cree', 'Cree'),
('cs', 'Czech', 'Tschechisch', 'tchèque', 'checo', 'Ceco'),
('cu', 'Old Slavonic', 'Kirchenslawisch', 'vieux slave', 'eslavo eclesiástico antiguo', 'Antico slavo ecclesiastico'),
('cv', 'Chuvash', 'Tschuwaschisch', 'tchouvache', 'chuvasio', 'Ciuvascio'),
('cy', 'Welsh', 'Kymrisch', 'gallois', 'galés', 'Gallese'),
('da', 'Danish', 'Dänisch', 'danois', 'danés', 'Danese'),
('de', 'German', 'Deutsch', 'allemand', 'alemán', 'Tedesco'),
('dv', 'Maldivian', 'Maledivisch', 'maldivien', 'maldivo', 'Divehi, Dhivehi, Maldiviano'),
('dz', 'Dzongkha', 'Dzongkha', 'dzongkha', 'dzongkha', 'Dzongkha'),
('ee', 'Ewe', 'Ewe-Sprache', 'éwé', 'ewe', 'Ewe'),
('el', 'Greek', 'Neugriechisch', 'grec moderne', 'griego', 'Greco, moderno'),
('en', 'English', 'Englisch', 'anglais', 'inglés', 'Inglese'),
('eo', 'Esperanto', 'Esperanto', 'espéranto', 'esperanto', 'Esperanto'),
('es', 'Spanish', 'Spanisch', 'espagnol', 'español', 'Spagnolo, Castigliano'),
('et', 'Estonian', 'Estnisch', 'estonien', 'estonio', 'Estone'),
('eu', 'Basque', 'Baskisch', 'basque', 'vascuence', 'Basco'),
('fa', 'Persian', 'Persisch', 'persan', 'persa', 'Persiano, Fārsì'),
('ff', 'Fulah', 'Ful', 'peul', 'fula', 'Fula, Fulah, Pulaar, Pular'),
('fi', 'Finnish', 'Finnisch', 'finnois', 'finés', 'Finlandese'),
('fj', 'Fijian', 'Fidschi-Sprache', 'fidjien', 'fijiano', 'Figiano'),
('fo', 'Faroese', 'Färöisch', 'féroïen', 'feroés', 'Faroese'),
('fr', 'French', 'Französisch', 'français', 'francés', 'Francese'),
('fy', 'Western Frisian', 'Friesisch', 'frison occidental', 'frisón', 'Frisone occidentale'),
('ga', 'Irish', 'Irisch', 'irlandais', 'irlandés', 'Irlandese'),
('gd', 'Gaelic', 'Gälisch-Schottisch', 'gaélique', 'gaélico escocés', 'Gaelico scozzese'),
('gl', 'Galician', 'Galicisch', 'galicien', 'gallego', 'Galiziano'),
('gn', 'Guarani', 'Guaraní-Sprache', 'guarani', 'guaraní', 'Guaraní'),
('gu', 'Gujarati', 'Gujarati-Sprache', 'goudjrati', 'guyaratí', 'Gujarati'),
('gv', 'Manx', 'Manx', 'manx; mannois', 'manés', 'Mannese'),
('ha', 'Hausa', 'Haussa-Sprache', 'haoussa', 'hausa', 'Hausa'),
('he', 'Hebrew', 'Hebräisch', 'hébreu', 'hebreo', 'Ebraico (moderno)'),
('hi', 'Hindi', 'Hindi', 'hindi', 'hindi', 'Hindi'),
('ho', 'Hiri Motu', 'Hiri-Motu', 'hiri motu', 'hiri motu', 'Hiri Motu'),
('hr', 'Croatian', 'Kroatisch', 'croate', 'croata', 'Croato'),
('ht', 'Haitian', 'Haïtien', 'haïtien', 'haitiano', 'Creolo haitiano'),
('hu', 'Hungarian', 'Ungarisch', 'hongrois', 'húngaro', 'Ungherese'),
('hy', 'Armenian', 'Armenisch', 'arménien', 'armenio', 'Armeno'),
('hz', 'Herero', 'Herero-Sprache', 'herero', 'herero', 'Herero'),
('ia', 'Interlingua', 'Interlingua', 'interlingua', 'interlingua', 'Interlingua'),
('id', 'Indonesian', 'Bahasa Indonesia', 'indonésien', 'indonesio', 'Indonesiano'),
('ie', 'Interlingue', 'Interlingue', 'interlingue', 'occidental', 'Interlingue'),
('ig', 'Igbo', 'Ibo-Sprache', 'igbo', 'igbo', 'Igbo'),
('ii', 'Sichuan Yi', 'Lalo-Sprache', 'yi de Sichuan', 'yi de Sichuán', 'Nuosu'),
('ik', 'Inupiaq', 'Inupik', 'inupiaq', 'inupiaq', 'Inupiaq'),
('io', 'Ido', 'Ido', 'ido', 'ido', 'Ido'),
('is', 'Icelandic', 'Isländisch', 'islandais', 'islandés', 'Islandese'),
('it', 'Italian', 'Italienisch', 'italien', 'italiano', 'Italiano'),
('iu', 'Inuktitut', 'Inuktitut', 'inuktitut', 'inuktitut', 'Inuktitut'),
('ja', 'Japanese', 'Japanisch', 'japonais', 'japonés', 'Giapponese'),
('jv', 'Javanese', 'Javanisch', 'javanais', 'javanés', 'Giavanese'),
('ka', 'Georgian', 'Georgisch', 'géorgien', 'georgiano', 'Georgiano'),
('kg', 'Kongo', 'Kongo-Sprache', 'kongo', 'kongo', 'Kikongo'),
('ki', 'Kikuyu', 'Kikuyu-Sprache', 'kikuyu', 'kikuyu', 'Kikuyu, Gikuyu'),
('kj', 'Kwanyama', 'Kwanyama-Sprache', 'kwanyama', 'kuanyama', 'Kuanyama'),
('kk', 'Kazakh', 'Kasachisch', 'kazakh', 'kazajo', 'Kazaco'),
('kl', 'Greenlandic', 'Grönländisch', 'groenlandais', 'groenlandés', 'Groenlandese'),
('km', 'Central Khmer', 'Kambodschanisch', 'khmer central', 'camboyano', 'Khmer'),
('kn', 'Kannada', 'Kannada', 'kannada', 'canarés', 'Kannada'),
('ko', 'Korean', 'Koreanisch', 'coréen', 'coreano', 'Coreano'),
('kr', 'Kanuri', 'Kanuri-Sprache', 'kanouri', 'kanuri', 'Kanuri'),
('ks', 'Kashmiri', 'Kaschmiri', 'kashmiri', 'cachemiro', 'Kashmiri'),
('ku', 'Kurdish', 'Kurdisch', 'kurde', 'kurdo', 'Curdo'),
('kv', 'Komi', 'Komi-Sprache', 'kom', 'komi', 'Komi'),
('kw', 'Cornish', 'Kornisch', 'cornique', 'córnico', 'Cornico'),
('ky', 'Kirghiz', 'Kirgisisch', 'kirghiz', 'kirguís', 'Chirghiso'),
('la', 'Latin', 'Latein', 'latin', 'latín', 'Latino'),
('lb', 'Luxembourgish', 'Luxemburgisch', 'luxembourgeois', 'luxemburgués', 'Lussemburghese'),
('lg', 'Ganda', 'Ganda-Sprache', 'ganda', 'luganda', 'Luganda'),
('li', 'Limburgish', 'Limburgisch', 'limbourgeois', 'limburgués', 'Limburghese'),
('ln', 'Lingala', 'Lingala', 'lingala', 'lingala', 'Lingala'),
('lo', 'Lao', 'Laotisch', 'lao', 'lao', 'Lao'),
('lt', 'Lithuanian', 'Litauisch', 'lituanien', 'lituano', 'Lituano'),
('lu', 'Luba-Katanga', 'Luba-Katanga-Sprache', 'luba-katanga', 'luba-katanga', 'Luba-Katanga'),
('lv', 'Latvian', 'Lettisch', 'letton', 'letón', 'Lettone'),
('mg', 'Malagasy', 'Malagassi-Sprache', 'malgache', 'malgache', 'Malgascio'),
('mh', 'Marshallese', 'Marschallesisch', 'marshall', 'marshalés', 'Marshallese'),
('mi', 'Maori', 'Maori-Sprache', 'maori', 'maorí', 'Maori'),
('mk', 'Macedonian', 'Makedonisch', 'macédonien', 'macedonio', 'Macedone'),
('ml', 'Malayalam', 'Malayalam', 'malayalam', 'malayalam', 'Malayalam'),
('mn', 'Mongolian', 'Mongolisch', 'mongol', 'mongol', 'Mongolo'),
('mr', 'Marathi', 'Marathi', 'marathe', 'maratí', 'Marathi'),
('ms', 'Malay', 'Malaiisch', 'malais', 'malayo', 'Malese'),
('mt', 'Maltese', 'Maltesisch', 'maltais', 'maltés', 'Maltese'),
('my', 'Burmese', 'Birmanisch', 'birman', 'birmano', 'Birmano'),
('na', 'Nauru', 'Nauruanisch', 'nauruan', 'nauruano', 'Nauruano'),
('nb', 'Norwegian', 'Bokmål', 'norvégien bokmål', 'noruego bokmål', 'Norvegese'),
('nd', 'North Ndebele', 'Ndebele-Sprache (Simbabwe)', 'ndébélé du Nord', 'ndebele del norte', 'Ndebele del Nord'),
('ne', 'Nepali', 'Nepali', 'népalais', 'nepalí', 'Nepalese'),
('ng', 'Ndonga', 'Ndonga', 'ndonga', 'ndonga', 'Ndonga'),
('nl', 'Dutch', 'Niederländisch', 'néerlandais', 'neerlandés', 'Olandese'),
('nn', 'Norwegian Nynorsk', 'Nynorsk', 'norvégien nynorsk', 'nynorsk', 'Norvegese Nynorsk'),
('no', 'Norwegian', 'Norwegisch', 'norvégien', 'noruego', 'Norvegese'),
('nr', 'South Ndebele', 'Ndebele-Sprache (Transvaal)', 'ndébélé du Sud', 'ndebele del sur', 'Ndebele del Sud'),
('nv', 'Navajo', 'Navajo-Sprache', 'navaho', 'navajo', 'Navajo, Navaho'),
('ny', 'Nyanja', 'Nyanja-Sprache', 'nyanja', 'chichewa', 'Nyanja'),
('oc', 'Occitan', 'Okzitanisch', 'occitan', 'occitano', 'Occitano'),
('oj', 'Ojibwa', 'Ojibwa-Sprache', 'ojibwa', 'ojibwa', 'Ojibwa'),
('om', 'Oromo', 'Galla-Sprache', 'galla', 'oromo', 'Oromo'),
('or', 'Oriya', 'Oriya-Sprache', 'oriya', 'oriya', 'Oriya'),
('os', 'Ossetic', 'Ossetisch', 'ossète', 'osético', 'Osseto'),
('pa', 'Punjabi', 'Pandschabi-Sprache', 'pendjabi', 'panyabí', 'Punjabi'),
('pi', 'Pali', 'Pali', 'pali', 'pali', 'Pāli'),
('pl', 'Polish', 'Polnisch', 'polonais', 'polaco', 'Polacco'),
('ps', 'Pashto', 'Paschtu', 'pachto', 'pashto', 'Pashtu'),
('pt', 'Portuguese', 'Portugiesisch', 'portugais', 'portugués', 'Portoghese'),
('qu', 'Quechua', 'Quechua-Sprache', 'quechua', 'quechua', 'Quechua'),
('rm', 'Romansh', 'Rätoromanisch', 'romanche', 'retorrománico', 'Romancio'),
('rn', 'Rundi', 'Rundi-Sprache', 'rundi', 'kirundi', 'Kirundi'),
('ro', 'Romanian', 'Rumänisch', 'roumain', 'rumano', 'Rumeno'),
('ru', 'Russian', 'Russisch', 'russe', 'ruso', 'Russo'),
('rw', 'Kinyarwanda', 'Rwanda-Sprache', 'rwanda', 'ruandés', 'Kinyarwanda'),
('sa', 'Sanskrit', 'Sanskrit', 'sanskrit', 'sánscrito', 'Sanscrito'),
('sc', 'Sardinian', 'Sardisch', 'sarde', 'sardo', 'Sardo'),
('sd', 'Sindhi', 'Sindhi-Sprache', 'sindhi', 'sindhi', 'Sindhi'),
('se', 'Northern Sami', 'Nordsaamisch', 'sami du Nord', 'sami septentrional', 'Sami settentrionale'),
('sg', 'Sango', 'Sango-Sprache', 'sango', 'sango', 'Sango'),
('si', 'Sinhalese', 'Singhalesisch', 'singhalais', 'cingalés', 'Singalese'),
('sk', 'Slovak', 'Slowakisch', 'slovaque', 'eslovaco', 'Slovacco'),
('sl', 'Slovenian', 'Slowenisch', 'slovène', 'esloveno', 'Sloveno'),
('sm', 'Samoan', 'Samoanisch', 'samoan', 'samoano', 'Samoano'),
('sn', 'Shona', 'Schona-Sprache', 'shona', 'shona', 'Shona'),
('so', 'Somali', 'Somali', 'somali', 'somalí', 'Somalo'),
('sq', 'Albanian', 'Albanisch', 'albanais', 'albanés', 'Albanese'),
('sr', 'Serbian', 'Serbisch', 'serbe', 'serbio', 'Serbo'),
('ss', 'Swati', 'Swasi-Sprache', 'swati', 'suazi', 'Swazi'),
('st', 'Southern Sotho', 'Süd-Sotho-Sprache', 'sotho du Sud', 'sesotho', 'Sesotho del Sud'),
('su', 'Sundanese', 'Sundanesisch', 'soundanais', 'sundanés', 'Sondanese'),
('sv', 'Swedish', 'Schwedisch', 'suédois', 'sueco', 'Svedese'),
('sw', 'Swahili', 'Swahili', 'swahili', 'suajili', 'Swahili'),
('ta', 'Tamil', 'Tamil', 'tamoul', 'tamil', 'Tamil'),
('te', 'Telugu', 'Telugu-Sprache', 'télougou', 'telugú', 'Telugu'),
('tg', 'Tajik', 'Tadschikisch', 'tadjik', 'tayiko', 'Tagiko'),
('th', 'Thai', 'Thailändisch', 'thaï', 'tailandés', 'Thailandese'),
('ti', 'Tigrinya', 'Tigrinja-Sprache', 'tigrigna', 'tigriña', 'Tigrino'),
('tk', 'Turkmen', 'Turkmenisch', 'turkmène', 'turcomano', 'Turkmeno'),
('tl', 'Tagalog', 'Tagalog', 'tagalog', 'tagalo', 'Tagalog'),
('tn', 'Tswana', 'Tswana-Sprache', 'tswana', 'setsuana', 'Tswana'),
('to', 'Tonga', 'Tongaisch', 'tongan', 'tongano', 'Tongano'),
('tr', 'Turkish', 'Türkisch', 'turc', 'turco', 'Turco'),
('ts', 'Tsonga', 'Tsonga-Sprache', 'tsonga', 'tsonga', 'Tsonga'),
('tt', 'Tatar', 'Tatarisch', 'tatar', 'tártaro', 'Tataro'),
('tw', 'Twi', 'Twi-Sprache', 'twi', 'twi', 'Twi'),
('ty', 'Tahitian', 'Tahitisch', 'tahitien', 'tahitiano', 'Tahitiano'),
('ug', 'Uighur', 'Uigurisch', 'ouïgour', 'uigur', 'Uiguro'),
('uk', 'Ukrainian', 'Ukrainisch', 'ukrainien', 'ucraniano', 'Ucraino'),
('ur', 'Urdu', 'Urdu', 'ourdou', 'urdu', 'Urdu'),
('uz', 'Uzbek', 'Usbekisch', 'ouszbek', 'uzbeko', 'Usbeco'),
('ve', 'Venda', 'Venda-Sprache', 'venda', 'venda', 'Venda'),
('vi', 'Vietnamese', 'Vietnamesisch', 'vietnamien', 'vietnamita', 'Vietnamita'),
('vo', 'Volapük', 'Volapük', 'volapük', 'volapük', 'Volapük'),
('wa', 'Walloon', 'Wallonisch', 'wallon', 'valón', 'Vallone'),
('wo', 'Wolof', 'Wolof-Sprache', 'wolof', 'wolof', 'Wolof'),
('xh', 'Xhosa', 'Xhosa-Sprache', 'xhosa', 'xhosa', 'Xhosa'),
('yi', 'Yiddish', 'Jiddisch', 'yiddish', 'yiddish', 'Yiddish'),
('yo', 'Yoruba', 'Yoruba-Sprache', 'yoruba', 'yoruba', 'Yoruba'),
('za', 'Zhuang', 'Zhuang', 'zhuang', 'zhuang', 'Zhuang'),
('zh', 'Chinese', 'Chinesisch', 'chinois', 'chino', 'Cinese'),
('zu', 'Zulu', 'Zulu-Sprache', 'zoulou', 'zulú', 'Zulu');

ALTER TABLE `world_languages`
  ADD PRIMARY KEY (`alpha2`);
